Add username and password inputs and implement complete onboarding process

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,22 +1,36 @@
-name: 'setup-homeassistant'
-description: 'Setup a Home Assistant container for testing'
+name: "setup-homeassistant"
+description: "Setup a Home Assistant container for testing"
 branding:
   icon: "terminal"
   color: "gray-dark"
 inputs:
+  username:
+    description: "Username for the admin user"
+    required: false
+    default: "admin"
+  password:
+    description: "Password for the admin user"
+    required: false
+    default: "admin123"
   tag:
-    description: 'The tag of Home Assistant to use'
+    description: "The tag of Home Assistant to use"
     required: false
-    default: 'dev'
+    default: "dev"
   config-dir:
-    description: 'Path to the config dir to be used'
+    description: "Path to the config dir to be used"
     required: false
-    default: ''
+    default: ""
   retry-limit:
-    description: 'number of maximum retries'
+    description: "number of maximum retries"
     required: false
-    default: 360
+    default: "360"
 outputs:
+  username:
+    description: "The username created for authentication"
+    value: ${{ steps.user.outputs.username }}
+  password:
+    description: "The password created for authentication"
+    value: ${{ steps.user.outputs.password }}
   url:
     description: "The URL that the test container is running on"
     value: ${{ steps.run.outputs.url }}
@@ -81,12 +95,16 @@ runs:
       id: user
       run: |
         echo "Creating authentication"
-        TOKEN=$(docker run --rm \
+        OUTPUT=$(docker run --rm \
           -v /tmp/combined_configuration:/config \
           -v ${{ github.action_path }}/scripts/create_token.py:/tmp/create_token.py \
+          -e USERNAME="${{ inputs.username }}" \
+          -e PASSWORD="${{ inputs.password }}" \
           ghcr.io/home-assistant/amd64-homeassistant:${{ steps.init.outputs.tag }} \
           python3 /tmp/create_token.py)
-        echo "token=$TOKEN" >> $GITHUB_OUTPUT
+        echo "$OUTPUT" | jq -r '"token=\(.access_token)" >> $GITHUB_OUTPUT'
+        echo "$OUTPUT" | jq -r '"username=\(.username)" >> $GITHUB_OUTPUT'
+        echo "$OUTPUT" | jq -r '"password=\(.password)" >> $GITHUB_OUTPUT'
 
     - shell: bash
       run: |
@@ -99,23 +117,23 @@ runs:
     - shell: bash
       id: run
       run: |
-          BASE_URL="http://127.0.0.1:8123"
-          echo "url=$BASE_URL" >> $GITHUB_OUTPUT
+        BASE_URL="http://127.0.0.1:8123"
+        echo "url=$BASE_URL" >> $GITHUB_OUTPUT
 
-          STATUS="false"
-          RETRIES=1
-          set +e
-          echo "Waiting for Home Assistant to start"
-          while true; do
-            STATUS=$(curl -sSL -H "Authorization: Bearer ${{ steps.user.outputs.token }}" "$BASE_URL/api/config" | jq -r .state)
-            if [ "$STATUS" == "RUNNING" ]; then
-              break
-            elif [ "$RETRIES" == "${{inputs.retry-limit}}" ]; then
-              echo "Failed to start"
-              docker logs ${{ steps.init.outputs.containername }}
-              exit 1
-            fi
-            sleep 1
-            RETRIES=$(( $RETRIES + 1 ))
-          done
-          set -e
+        STATUS="false"
+        RETRIES=1
+        set +e
+        echo "Waiting for Home Assistant to start"
+        while true; do
+          STATUS=$(curl -sSL -H "Authorization: Bearer ${{ steps.user.outputs.token }}" "$BASE_URL/api/config" | jq -r .state)
+          if [ "$STATUS" == "RUNNING" ]; then
+            break
+          elif [ "$RETRIES" == "${{inputs.retry-limit}}" ]; then
+            echo "Failed to start"
+            docker logs ${{ steps.init.outputs.containername }}
+            exit 1
+          fi
+          sleep 1
+          RETRIES=$(( $RETRIES + 1 ))
+        done
+        set -e
